#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/mp_system_user_module_db
#    username: postgres
#    password: 1
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#  sql:
#    init:
#      platform: postgres
#      mode: never
#      data-locations: classpath:init-schema.sql

server:
  port: 8080
#  servlet:
#    context-path: /api

application:
  security:
    jwt:
      secret-key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      expiration: 86400000
      refresh-token:
        expiration: 604800000

cors:
  allowedOrigins: "51.250.114.199:8080"
  allowedMethods: "GET, POST, PUT, DELETE"
  allowedHeaders: "*"
  allowedCredentials: true
  corsConfiguration: "/**"
  maxAge: 3600

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true